# Default values for datapower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: pihole/pihole
  tag: 4.2.2-1
  pullPolicy: IfNotPresent

persistence:
  ## Enables persistent volume - PV provisioner support necessary
  enabled: true
  ## Keep persistent volume after helm delete
  keep: false
  ## PVC Access Mode
  accessMode: ReadWriteMany
  ## PVC Size
  size: 5Gi

configData: |-
  address=/norseamerican.com/192.168.2.240
  address=/pi.hole/192.168.2.240

ingress:
  host: dns.norseamerican.com

environment:
  - name: TZ
    value: 'America/Boise'
  - name: WEBPASSWORD
    value: password

dns:
  - 127.0.0.1
  - 1.1.1.1
