apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name}}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        stdin: true
        tty: true
        resources:
          limits:
            memory: 1Gi
        env:
        - name: 'ServerIP'
          value: '0.0.0.0'
        - name: 'DNS1'
          value: '8.8.8.8'
        - name: 'DNS2'
          value: '1.1.1.1'
        {{- if .Values.environment }}
{{ toYaml .Values.environment | indent 8 }}
        {{- end -}}
        {{- if .Values.dns -}}
        dns:
{{ toYaml .Values.dns | indent 8 }}
        {{- end -}}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: dns1
          containerPort: 53
          protocol: TCP 
        - name: dns2
          containerPort: 53
          protocol: UDP
        volumeMounts:
            - name: pvc
              mountPath: "/etc/pihole"
              subPath: "pihole"
            - name: pvc
              mountPath: "/etc/dnsmasq.d"
              subPath: "dnsmasq"
            - name: config
              mountPath: "/etc/dnsmasq.d/05-custom.conf"
              subPath: 05-custom.conf
            - name: config
              mountPath: "/etc/pihole/whitelist.txt"
              subPath: whitelist.txt
            - name: config
              mountPath: "/etc/pihole/adlists.list"
              subPath: adlists.list
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}-config
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}-pvc
